### ISSUE TITLE
Apostrophes showing as two single quotes in json

### ISSUE THREAD

**Issue by trevasco** [chanzuckerberg/meta-kg-api-documentation#6]
e.g. Parkinson''s.

example:
https://api.meta.org/work?filter=pmid:32043803
https://www.meta.org/papers/risk-factors-for-earlier-dementia-onset-in/32043803

**Comment by jenniferlin15** [comment]
Confirmed and replicated bug. Investigating and will share further details as we get a handle on root cause.

**Comment by jenniferlin15** [comment]
Fixed bug so that apostrophe's appear correctly in the JSON response.
