### ISSUE TITLE
Frequently see contributors listed multiple times in works

### ISSUE THREAD

**Issue by trevasco** [chanzuckerberg/meta-kg-api-documentation#7]
example:
https://api.meta.org/work?filter=pmid:33884297
https://www.meta.org/papers/african-americans-have-differences-in-csf-soluble/33884297

**Comment by jenniferlin15** [comment]
Confirmed and replicated bug. Investigating this now and will share out further details.

**Comment by jenniferlin15** [comment]
Fixed contributor duplication and also display contributors in order of their author index (sequenced by author list).
