### ISSUE TITLE
'UNKNOWN' appearing in front of listed contributors

### ISSUE THREAD

**Issue by trevasco** [chanzuckerberg/meta-kg-api-documentation#8]
examples:
https://api.meta.org/work?filter=pmid:32172342
https://api.meta.org/work?filter=pmid:30820047
https://api.meta.org/work?filter=pmid:31160810

**Comment by jenniferlin15** [comment]
Thanks so much for logging this. Comparing it to our data source, this is a bug introduced by us (not by the data source). Seems to be occurring with group names (ex: 23andMe, Genetic and Environmental Risk in AD/Defining Genetic, Polygenic and Environmental Risk for Alzheimer’s Disease Consortium). Will investigate and share further details.

**Comment by jenniferlin15** [comment]
Bug is fixed. Unknown is not appearing in front of contributor name.
